swagger:
	@echo
	@echo "--- OPEN THIS LINK TO VIEW SWAGGER DOCS ---"
	@echo "http://localhost:8080/?url=http://localhost:8080/mnt/swagger.yml"
	@echo
	docker run -p 8080:8080 -v `pwd`:/usr/share/nginx/html/mnt swaggerapi/swagger-editor
